---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r, data, echo=FALSE}
library(tidyverse)
library(sjPlot)
library(brms)
library(parallel)
library(interactions)
library(jtools)

main_effect_updated<-read_csv(
  "modelling_data_exploratory.csv"
)
ncores = detectCores()
```


```{r, home, echo=FALSE}
mainEffect<-main_effect_updated %>%
  dplyr::select(id, accepted, StartDateConvert, 
                MediaUse.scaled, 
                MediaUse.mean,
                demog_sex_recoded, demog_age.z, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, lagged_accepted.cz, overall_study_day, 
                home.mean, 
                home.scaled) %>% na.omit() %>% dplyr::distinct()

homeContext_use<-brm(accepted ~
                         ((MediaUse.scaled+
                             MediaUse.mean)*
                            (home.scaled+ 
                               home.mean))+
                         demog_sex_recoded+demog_age.z+weekend+nAct.cz+surveys_per_id.z+overall_study_day+
                         (lagDur.cz*lagged_accepted.cz)+
                         (1+MediaUse.scaled*home.scaled| id),
                       data=mainEffect,family=gaussian(),
                       seed = 1234, cores=ncores, iter=12000)

summary(homeContext_use)

mainEffect<-main_effect_updated %>%
  dplyr::select(id, accepted, StartDateConvert, 
                socialmedia.cz, 
                socialmedia.bp.z,
                demog_sex_recoded, demog_age.z, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, lagged_accepted.cz, overall_study_day, 
                home.mean, 
                home.scaled) %>% na.omit() %>% dplyr::distinct()

homeContext_duration<-brm(accepted ~
                              ((socialmedia.cz+socialmedia.bp.z)*
                                 (home.scaled+ home.mean))+
                              demog_sex_recoded+demog_age.z+weekend+nAct.cz+surveys_per_id.z+overall_study_day+ (lagDur.cz*lagged_accepted.cz)+
                              (1+socialmedia.cz*home.scaled| id),
                            data=mainEffect,family=gaussian(),
                            seed = 1234, cores=ncores, iter=12000)

summary(homeContext_duration)
```


```{r, social, echo=FALSE}
mainEffect<-main_effect_updated %>%
  dplyr::select(id, accepted, StartDateConvert, 
                MediaUse.scaled, 
                MediaUse.mean,
                demog_sex_recoded, demog_age.z, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, lagged_accepted.cz, overall_study_day, 
                home_socialNumeric.mean, 
                home_socialNumeric.scaled) %>% na.omit() %>% dplyr::distinct()

socialContext_use<-brm(accepted ~
                         ((MediaUse.scaled+
                             MediaUse.mean)*
                            (home_socialNumeric.scaled+ 
                               home_socialNumeric.mean))+
                         demog_sex_recoded+demog_age.z+weekend+nAct.cz+surveys_per_id.z+overall_study_day+
                         (lagDur.cz*lagged_accepted.cz)+
                         (1+MediaUse.scaled*home_socialNumeric.scaled| id),
                       data=mainEffect,family=gaussian(),
                       seed = 1234, cores=ncores, iter=12000)

summary(socialContext_use)

mainEffect<-main_effect_updated %>%
  dplyr::select(id, accepted, StartDateConvert, 
                socialmedia.cz, 
                socialmedia.bp.z,
                demog_sex_recoded, demog_age.z, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, lagged_accepted.cz, overall_study_day, 
                home_socialNumeric.mean, 
                home_socialNumeric.scaled) %>% na.omit() %>% dplyr::distinct()

socialContext_duration<-brm(accepted ~
                              ((socialmedia.cz+socialmedia.bp.z)*
                                 (home_socialNumeric.scaled+ home_socialNumeric.mean))+
                              demog_sex_recoded+demog_age.z+weekend+nAct.cz+surveys_per_id.z+overall_study_day+ (lagDur.cz*lagged_accepted.cz)+
                              (1+socialmedia.cz*home_socialNumeric.scaled| id),
                            data=mainEffect,family=gaussian(),
                            seed = 1234, cores=ncores, iter=12000)

summary(socialContext_duration)
```

```{r, nature, echo=FALSE}
mainEffect<-main_effect_updated %>%
  dplyr::select(id, accepted, StartDateConvert, 
                MediaUse.scaled, 
                MediaUse.mean,
                demog_sex_recoded, demog_age.z, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, lagged_accepted.cz, overall_study_day, 
                home_natureNumeric.mean, 
                home_natureNumeric.scaled) %>% na.omit() %>% dplyr::distinct()


natureContext_use<-brm(accepted ~
                         ((MediaUse.scaled+MediaUse.mean)*
                            (home_natureNumeric.scaled+ home_natureNumeric.mean))+
                         demog_sex_recoded+demog_age.z+weekend+nAct.cz+surveys_per_id.z+overall_study_day+(lagDur.cz*lagged_accepted.cz)+
                         (1+MediaUse.scaled*home_natureNumeric.scaled| id),
                       data=mainEffect,family=gaussian(),
                       seed = 1234, cores= 10, iter=12000)

summary(natureContext_use)

mainEffect<-main_effect_updated %>%
  dplyr::select(id, accepted, StartDateConvert, 
                socialmedia.cz, 
                socialmedia.bp.z,
                demog_sex_recoded, demog_age.z, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, lagged_accepted.cz, overall_study_day, 
                home_natureNumeric.mean, 
                home_natureNumeric.scaled) %>% na.omit() %>% dplyr::distinct()

natureContext_duration<-brm(accepted ~
                              ((socialmedia.cz+socialmedia.bp.z)*
                                 (home_natureNumeric.scaled+ home_natureNumeric.mean))+
                              demog_sex_recoded+demog_age.z+weekend+nAct.cz+surveys_per_id.z+overall_study_day+(lagDur.cz*lagged_accepted.cz)+
                              (1+socialmedia.cz*home_natureNumeric.scaled| id),
                            data=mainEffect,family=gaussian(),
                            seed = 1234, cores=ncores, iter=12000)

summary(natureContext_duration)
```

```{r, transit, echo=FALSE}
mainEffect<-main_effect_updated %>%
  dplyr::select(id, accepted, StartDateConvert, 
                MediaUse.scaled, 
                MediaUse.mean,
                demog_sex_recoded, demog_age.z, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, lagged_accepted.cz, overall_study_day, 
                home_transitNumeric.mean, 
                home_transitNumeric.scaled) %>% na.omit() %>% dplyr::distinct()


transitContext_use<-brm(accepted ~
                          ((MediaUse.scaled+MediaUse.mean)*
                             (home_transitNumeric.scaled+ home_transitNumeric.mean))+
                          demog_sex_recoded+demog_age.z+weekend+nAct.cz+surveys_per_id.z+overall_study_day+ (lagDur.cz*lagged_accepted.cz)+
                          (1+MediaUse.scaled*home_transitNumeric.scaled| id),
                        data=mainEffect,family=gaussian(),
                        seed = 1234, cores=ncores, iter=12000)

summary(transitContext_use)

mainEffect<-main_effect_updated %>%
  dplyr::select(id, accepted, StartDateConvert, 
                socialmedia.cz, 
                socialmedia.bp.z,
                demog_sex_recoded, demog_age.z, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, lagged_accepted.cz, overall_study_day, 
                home_transitNumeric.mean, 
                home_transitNumeric.scaled) %>% na.omit() %>% dplyr::distinct()

transitContext_duration<-brm(accepted ~
                               ((socialmedia.cz+socialmedia.bp.z)*
                                  (home_transitNumeric.scaled+ home_transitNumeric.mean))+
                               demog_sex_recoded+demog_age.z+weekend+nAct.cz+surveys_per_id.z+overall_study_day+  (lagDur.cz*lagged_accepted.cz)+
                               (1+socialmedia.cz*home_transitNumeric.scaled| id),
                             data=mainEffect,family=gaussian(),
                             seed = 1234, cores=ncores, iter=12000)

summary(transitContext_duration)
```

```{r, work, echo=FALSE}
mainEffect<-main_effect_updated %>%
  dplyr::select(id, accepted, StartDateConvert, 
                MediaUse.scaled, 
                MediaUse.mean,
                demog_sex_recoded, demog_age.z, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, lagged_accepted.cz, overall_study_day, 
                home_workNumeric.mean, 
                home_workNumeric.scaled) %>% na.omit() %>% dplyr::distinct()


workContext_use<-brm(accepted ~
                       ((MediaUse.scaled+MediaUse.mean)*
                          (home_workNumeric.scaled+ home_workNumeric.mean))+
                       demog_sex_recoded+demog_age.z+weekend+nAct.cz+surveys_per_id.z+overall_study_day+(lagDur.cz*lagged_accepted.cz)+
                       (1+MediaUse.scaled*home_workNumeric.scaled| id),
                     data=mainEffect,family=gaussian(),
                     seed = 1234, cores=ncores, iter=12000)

summary(workContext_use)


mainEffect<-main_effect_updated %>%
  dplyr::select(id, accepted, StartDateConvert, 
                socialmedia.cz, 
                socialmedia.bp.z,
                demog_sex_recoded, demog_age.z, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, lagged_accepted.cz, overall_study_day, 
                home_workNumeric.mean, 
                home_workNumeric.scaled) %>% na.omit() %>% dplyr::distinct()

workContext_duration<-brm(accepted ~
                            ((socialmedia.cz+socialmedia.bp.z)*
                               (home_workNumeric.scaled+ home_workNumeric.mean))+
                            demog_sex_recoded+demog_age.z+weekend+nAct.cz+surveys_per_id.z+overall_study_day+(lagDur.cz*lagged_accepted.cz)+
                            (1+socialmedia.cz*home_workNumeric.scaled| id),
                          data=mainEffect,family=gaussian(),
                          seed = 1234, cores=ncores, iter=12000)

summary(workContext_duration)
```

```{r, religion, echo=FALSE}
mainEffect<-main_effect_updated %>%
  dplyr::select(id, accepted, StartDateConvert, 
                MediaUse.scaled, 
                MediaUse.mean,
                demog_sex_recoded, demog_age.z, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, lagged_accepted.cz, overall_study_day, 
                home_religionNumeric.mean, 
                home_religionNumeric.scaled) %>% na.omit() %>% dplyr::distinct()


religionContext_use<-brm(accepted ~
                         ((MediaUse.scaled+MediaUse.mean)*
                            (home_religionNumeric.scaled+ home_religionNumeric.mean))+
                         demog_sex_recoded+demog_age.z+weekend+nAct.cz+surveys_per_id.z+overall_study_day+(lagDur.cz*lagged_accepted.cz)+
                         (1+MediaUse.scaled*home_religionNumeric.scaled| id),
                       data=mainEffect,family=gaussian(),
                       seed = 1234, cores= 10, iter=12000)

summary(religionContext_use)


mainEffect<-main_effect_updated %>%
  dplyr::select(id, accepted, StartDateConvert, 
                socialmedia.cz, 
                socialmedia.bp.z,
                demog_sex_recoded, demog_age.z, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, lagged_accepted.cz, overall_study_day, 
                home_religionNumeric.mean, 
                home_religionNumeric.scaled) %>% na.omit() %>% dplyr::distinct()

religionContext_duration<-brm(accepted ~
                              ((socialmedia.cz+socialmedia.bp.z)*
                                 (home_religionNumeric.scaled+ home_religionNumeric.mean))+
                              demog_sex_recoded+demog_age.z+weekend+nAct.cz+surveys_per_id.z+overall_study_day+(lagDur.cz*lagged_accepted.cz)+
                              (1+socialmedia.cz*home_religionNumeric.scaled| id),
                            data=mainEffect,family=gaussian(),
                            seed = 1234, cores=ncores, iter=12000)

summary(religionContext_duration)
```

```{r, study, echo=FALSE}

mainEffect<-main_effect_updated %>%
  dplyr::select(id, accepted, StartDateConvert, 
                MediaUse.scaled, 
                MediaUse.mean,
                demog_sex_recoded, demog_age.z, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, lagged_accepted.cz, overall_study_day, 
                home_studyNumeric.mean, 
                home_studyNumeric.scaled) %>% na.omit() %>% dplyr::distinct()


studyContext_use<-brm(accepted ~
                         ((MediaUse.scaled+MediaUse.mean)*
                            (home_studyNumeric.scaled+ home_studyNumeric.mean))+
                         demog_sex_recoded+demog_age.z+weekend+nAct.cz+surveys_per_id.z+overall_study_day+(lagDur.cz*lagged_accepted.cz)+
                         (1+MediaUse.scaled*home_studyNumeric.scaled| id),
                       data=mainEffect,family=gaussian(),
                       seed = 1234, cores= 10, iter=12000)

summary(studyContext_use)


mainEffect<-main_effect_updated %>%
  dplyr::select(id, accepted, StartDateConvert, 
                socialmedia.cz, 
                socialmedia.bp.z,
                demog_sex_recoded, demog_age.z, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, lagged_accepted.cz, overall_study_day, 
                home_studyNumeric.mean, 
                home_studyNumeric.scaled) %>% na.omit() %>% dplyr::distinct()

studyContext_duration<-brm(accepted ~
                              ((socialmedia.cz+socialmedia.bp.z)*
                                 (home_studyNumeric.scaled+ home_studyNumeric.mean))+
                              demog_sex_recoded+demog_age.z+weekend+nAct.cz+surveys_per_id.z+overall_study_day+(lagDur.cz*lagged_accepted.cz)+
                              (1+socialmedia.cz*home_studyNumeric.scaled| id),
                            data=mainEffect,family=gaussian(),
                            seed = 1234, cores=ncores, iter=12000)

summary(studyContext_duration)
```


```{r, gym, echo=FALSE}
mainEffect<-main_effect_updated %>%
  dplyr::select(id, accepted, StartDateConvert, 
                MediaUse.scaled, 
                MediaUse.mean,
                demog_sex_recoded, demog_age.z, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, lagged_accepted.cz, overall_study_day, 
                home_gymNumeric.mean, 
                home_gymNumeric.scaled) %>% na.omit() %>% dplyr::distinct()


gymContext_use<-brm(accepted ~
                         ((MediaUse.scaled+MediaUse.mean)*
                            (home_gymNumeric.scaled+ home_gymNumeric.mean))+
                         demog_sex_recoded+demog_age.z+weekend+nAct.cz+surveys_per_id.z+overall_study_day+(lagDur.cz*lagged_accepted.cz)+
                         (1+MediaUse.scaled*home_gymNumeric.scaled| id),
                       data=mainEffect,family=gaussian(),
                       seed = 1234, cores= 10, iter=12000)

summary(gymContext_use)


mainEffect<-main_effect_updated %>%
  dplyr::select(id, accepted, StartDateConvert, 
                socialmedia.cz, 
                socialmedia.bp.z,
                demog_sex_recoded, demog_age.z, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, lagged_accepted.cz, overall_study_day, 
                home_gymNumeric.mean, 
                home_gymNumeric.scaled) %>% na.omit() %>% dplyr::distinct()

gymContext_duration<-brm(accepted ~
                              ((socialmedia.cz+socialmedia.bp.z)*
                                 (home_gymNumeric.scaled+ home_gymNumeric.mean))+
                              demog_sex_recoded+demog_age.z+weekend+nAct.cz+surveys_per_id.z+overall_study_day+(lagDur.cz*lagged_accepted.cz)+
                              (1+socialmedia.cz*home_gymNumeric.scaled| id),
                            data=mainEffect,family=gaussian(),
                            seed = 1234, cores=ncores, iter=12000)

summary(gymContext_duration)
```

```{r, alone, echo=FALSE}
mainEffect<-main_effect_updated %>%
  dplyr::select(id, accepted, StartDateConvert, 
                MediaUse.scaled, 
                MediaUse.mean,
                demog_sex_recoded, demog_age.z, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, lagged_accepted.cz, overall_study_day, 
                alone.mean, 
                alone.scaled) %>% na.omit() %>% dplyr::distinct()

aloneContext_use<-brm(accepted ~
                         ((MediaUse.scaled+
                             MediaUse.mean)*
                            (alone.scaled+ 
                               alone.mean))+
                         demog_sex_recoded+demog_age.z+weekend+nAct.cz+surveys_per_id.z+overall_study_day+
                         (lagDur.cz*lagged_accepted.cz)+
                         (1+MediaUse.scaled*alone.scaled| id),
                       data=mainEffect,family=gaussian(),
                       seed = 1234, cores=ncores, iter=12000)

summary(aloneContext_use)

mainEffect<-main_effect_updated %>%
  dplyr::select(id, accepted, StartDateConvert, 
                socialmedia.cz, 
                socialmedia.bp.z,
                demog_sex_recoded, demog_age.z, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, lagged_accepted.cz, overall_study_day, 
                alone.mean, 
                alone.scaled) %>% na.omit() %>% dplyr::distinct()

aloneContext_duration<-brm(accepted ~
                             ((socialmedia.cz+socialmedia.bp.z)*
                                 (alone.scaled+ alone.mean))+
                              demog_sex_recoded+demog_age.z+weekend+nAct.cz+surveys_per_id.z+overall_study_day+
                             (lagDur.cz*lagged_accepted.cz)+
                              (1+socialmedia.cz*alone.scaled| id),
                       data=mainEffect,family=gaussian(),
                       seed = 1234, cores=ncores, iter=12000)

summary(aloneContext_duration)
```


```{r, close-ties, echo=FALSE}
mainEffect<-main_effect_updated %>%
  dplyr::select(id, accepted, StartDateConvert, 
                MediaUse.scaled, 
                MediaUse.mean,
                demog_sex_recoded, demog_age.z, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, lagged_accepted.cz, overall_study_day, 
                closeTiesNumeric.mean, 
                closeTiesNumeric.scaled) %>% na.omit() %>% dplyr::distinct()


closeTiesSocialContext_use<-brm(accepted ~
                                  ((MediaUse.scaled+MediaUse.mean)*
                                     (closeTiesNumeric.scaled+ closeTiesNumeric.mean))+
                                  demog_sex_recoded+demog_age.z+weekend+nAct.cz+surveys_per_id.z+overall_study_day+ (lagDur.cz*lagged_accepted.cz)+
                                  (1+MediaUse.scaled*closeTiesNumeric.scaled| id),
                                data=mainEffect,family=gaussian(),
                                seed = 1234, cores=ncores, iter=12000)

summary(closeTiesSocialContext_use)

mainEffect<-main_effect_updated %>%
  dplyr::select(id, accepted, StartDateConvert, 
                socialmedia.cz, 
                socialmedia.bp.z,
                demog_sex_recoded, demog_age.z, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, lagged_accepted.cz, overall_study_day, 
                closeTiesNumeric.mean, 
                closeTiesNumeric.scaled) %>% na.omit() %>% dplyr::distinct()

closeTiesSocialContext_duration<-brm(accepted ~
                                        ((socialmedia.cz+socialmedia.bp.z)*
                                           (closeTiesNumeric.scaled+ closeTiesNumeric.mean))+
                                        demog_sex_recoded+demog_age.z+weekend+nAct.cz+surveys_per_id.z+overall_study_day+(lagDur.cz*lagged_accepted.cz)+
                                        (1+socialmedia.cz*closeTiesNumeric.scaled| id),
                                      data=mainEffect,family=gaussian(),
                                      seed = 1234, cores=ncores, iter=12000)

summary(closeTiesSocialContext_duration)
```

```{r, distant-ties, echo=FALSE}
mainEffect<-main_effect_updated %>%
  dplyr::select(id, accepted, StartDateConvert, 
                MediaUse.scaled, 
                MediaUse.mean,
                demog_sex_recoded, demog_age.z, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, lagged_accepted.cz, overall_study_day, 
                distantTiesNumeric.mean, 
                distantTiesNumeric.scaled) %>% na.omit() %>% dplyr::distinct()


distantTiesSocialContext_use<-brm(accepted ~
                                    ((MediaUse.scaled+MediaUse.mean)*
                                       (distantTiesNumeric.scaled+ distantTiesNumeric.mean))+
                                    demog_sex_recoded+demog_age.z+weekend+nAct.cz+surveys_per_id.z+overall_study_day+(lagDur.cz*lagged_accepted.cz)+
                                    (1+MediaUse.scaled*distantTiesNumeric.scaled| id),
                                  data=mainEffect,family=gaussian(),
                                  seed = 1234, cores=ncores, iter=12000)

summary(distantTiesSocialContext_use)

mainEffect<-main_effect_updated %>%
  dplyr::select(id, accepted, StartDateConvert, 
                socialmedia.cz, 
                socialmedia.bp.z,
                demog_sex_recoded, demog_age.z, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, lagged_accepted.cz, overall_study_day, 
                distantTiesNumeric.mean, 
                distantTiesNumeric.scaled) %>% na.omit() %>% dplyr::distinct()

### 3 divergent transitions, increase adapt_delata above 0.8
distantTiesSocialContext_duration<-brm(accepted ~
                                         ((socialmedia.cz+socialmedia.bp.z)*
                                            (distantTiesNumeric.scaled+ distantTiesNumeric.mean))+
                                         demog_sex_recoded+demog_age.z+weekend+nAct.cz+surveys_per_id.z+overall_study_day+ (lagDur.cz*lagged_accepted.cz)+
                                         (1+socialmedia.cz*distantTiesNumeric.scaled| id),
                                       data=mainEffect,family=gaussian(),
                                       seed = 1234, cores=ncores, iter=12000)

summary(distantTiesSocialContext_duration)
```

```{r, family-ties, echo=FALSE}
mainEffect<-main_effect_updated %>%
  dplyr::select(id, accepted, StartDateConvert, 
                MediaUse.scaled, 
                MediaUse.mean,
                demog_sex_recoded, demog_age.z, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, lagged_accepted.cz, overall_study_day, 
                familyTiesNumeric.mean, 
                familyTiesNumeric.scaled) %>% na.omit() %>% dplyr::distinct()

familyTiesSocialContext_use<-brm(accepted ~
                                   ((MediaUse.scaled+MediaUse.mean)*
                                      (familyTiesNumeric.scaled+ familyTiesNumeric.mean))+
                                   demog_sex_recoded+demog_age.z+weekend+nAct.cz+surveys_per_id.z+overall_study_day+(lagDur.cz*lagged_accepted.cz)+
                                   (1+MediaUse.scaled*familyTiesNumeric.scaled| id),
                                 data=mainEffect,family=gaussian(),
                                 seed = 1234, cores=ncores, iter=12000)

summary(familyTiesSocialContext_use)


mainEffect<-main_effect_updated %>%
  dplyr::select(id, accepted, StartDateConvert, 
                socialmedia.cz, 
                socialmedia.bp.z,
                demog_sex_recoded, demog_age.z, weekend, nAct.cz, surveys_per_id.z, lagDur.cz, lagged_accepted.cz, overall_study_day, 
                familyTiesNumeric.mean, 
                familyTiesNumeric.scaled) %>% na.omit() %>% dplyr::distinct()

familyTiesSocialContext_duration<-brm(accepted ~
                                        ((socialmedia.cz+socialmedia.bp.z)*
                                           (familyTiesNumeric.scaled+ familyTiesNumeric.mean))+
                                        demog_sex_recoded+demog_age.z+weekend+nAct.cz+surveys_per_id.z+overall_study_day+(lagDur.cz*lagged_accepted.cz)+
                                        (1+socialmedia.cz*familyTiesNumeric.scaled| id),
                                      data=mainEffect,family=gaussian(),
                                      seed = 1234, cores=ncores, iter=12000)

summary(familyTiesSocialContext_duration)
```

```{r, sig-results, echo=FALSE}
summary(aloneContext_use) ## Significant
plot1<-interactions::interact_plot(aloneContext_use, pred="MediaUse.scaled", modx="alone.scaled")
plot1<-plot1+xlab("Social Media Use (vs Non-Use)")+ylab("Feelings of Being Accepted")+ggtitle("Alone(WP)")
ggsave("Interact: Alone x Use.pdf")
plot2<-interactions::johnson_neyman(aloneContext_use, pred="MediaUse.scaled", modx="alone.scaled")
plot2<-plot2$plot+theme_apa()+xlab("Alone (vs other interaction partners)")+ylab("Slope of Social Media Use (vs Non-Use) and Accepted")
ggsave("JN: Alone x Use.pdf")
plot1
plot2
```

```{r, sig-results-2, echo=FALSE}
summary(aloneContext_use) ## Significant
plot1<-interactions::interact_plot(aloneContext_use, pred="MediaUse.scaled", modx="alone.mean")
plot1<-plot1+theme_apa()+xlab("Social Media Use (vs Non-Use) (WP)") + ylab("Feelings of Being Accepted") + ggtitle("Alone(BP)")
plot1
ggsave("Interact: Alone [bp] x Use.pdf")
plot2<-interactions::johnson_neyman(aloneContext_use, pred="MediaUse.scaled", modx="alone.mean")
plot2<-plot2$plot + xlab("Alone (BP)") + ylab("Slope of Social Media Use (vs Non-Use) and Accepted")
plot2
ggsave("JN: Alone [bp] x Use.pdf")
```

```{r, sig-results-3, echo=FALSE}
summary(closeTiesSocialContext_use) ## Significant
plot1<-interactions::interact_plot(closeTiesSocialContext_use, pred="MediaUse.scaled", modx="closeTiesNumeric.scaled")
plot1<-plot1+xlab("Social Media Use (vs Non-Use) (WP)") + ylab("Feelings of Being Accepted") + ggtitle("Close Ties (WP)")
plot1
ggsave("Interact: CloseTies x Use.pdf")
plot2<-interactions::johnson_neyman(closeTiesSocialContext_use, pred="MediaUse.scaled", modx="closeTiesNumeric.scaled")
plot2<-plot2$plot+xlab("Close Ties (WP)")+ylab("Slope of Social Media Use (vs Non-Use) and Accepted")
plot2
ggsave("JN: CloseTies x Use.pdf")
```

```{r, sig-results-4, echo=FALSE}
summary(distantTiesSocialContext_use) ## Significant
plot1<-interactions::interact_plot(distantTiesSocialContext_use, pred="MediaUse.scaled", modx="distantTiesNumeric.mean")
plot1<-plot1+theme_apa()+xlab("Social Media Use (vs Non-Use) (WP)") + ylab("Feelings of Being Accepted") + ggtitle("Distant Ties (WP)")
plot1
ggsave("Interact: Distant Ties (BP) x Use.pdf")
plot2<-interactions::johnson_neyman(distantTiesSocialContext_use, pred="MediaUse.scaled", modx="distantTiesNumeric.mean")
plot2<-plot2$plot+theme_apa()+xlab("Distant Ties (WP)")+ylab("Slope of Social Media Use (vs Non-Use) and Accepted")
plot2
ggsave("JN: Distant Ties (BP) x Use.pdf")
```

```{r, sig-results-5, echo=FALSE}
summary(familyTiesSocialContext_use) ## Significant
plot1<-interactions::interact_plot(familyTiesSocialContext_use, pred="MediaUse.scaled", modx="familyTiesNumeric.scaled")
plot1<-plot1+theme_apa()+xlab("Social Media Use (vs Non-Use)(WP)")+ylab("Feelings of Being Accepted")+ggtitle("Family Ties (WP)")
plot1
ggsave("Interact: Family Ties x Use.pdf")
plot2<-interactions::johnson_neyman(familyTiesSocialContext_use, pred="MediaUse.scaled", modx="familyTiesNumeric.scaled")
plot2<-plot2$plot+theme_apa()+xlab("Family Ties (WP)") +ylab("Slope of Social Media Use (vs Non-Use) and Accepted")
plot2
ggsave("JN: Family Ties x Use.pdf")
```

```{r, sig-results-6, echo=FALSE}
summary(natureContext_use) ## Significant
plot1<-interactions::interact_plot(natureContext_use, pred="MediaUse.scaled", modx="home_natureNumeric.scaled")
plot1<-plot1+theme_apa()+xlab("Social Media Use (vs Non-Use) (WP)")+ylab("Feelings of Being Accepted")+ggtitle("Nature Location (WP)")
plot1
ggsave("Interact: Nature (BP) x Use.pdf")
plot2<-interactions::johnson_neyman(natureContext_use, pred="MediaUse.scaled", modx="home_natureNumeric.scaled")
plot2<-plot2$plot+theme_apa()+xlab("Nature Locations (WP)") +ylab("Slope of Social Media Use (vs Non-Use) and Accepted")
plot2
ggsave("JN: Nature (BP) x Use.pdf")
```

```{r, sig-results-7, echo=FALSE}
summary(socialContext_use) ## Significant
plot1<-interactions::interact_plot(socialContext_use, pred="MediaUse.scaled", modx="home_socialNumeric.scaled")
plot1<-plot1+theme_apa()+xlab("Social Media Use (vs Non-Use) (WP)")+ylab("Feelings of Being Accepted")+ggtitle("Social Location (WP)")
plot1
ggsave("Interact: Social x Use.pdf")
plot2<-interactions::johnson_neyman(socialContext_use, pred="MediaUse.scaled", modx="home_socialNumeric.scaled")
plot2<-plot2$plot+theme_apa()+xlab("Social Locations (WP)") +ylab("Slope of Social Media Use (vs Non-Use) and Accepted")
plot2
ggsave("JN: Social x Use.pdf")
```

```{r, sig-results-8, echo=FALSE}
summary(familyTiesSocialContext_duration) ## Significant
plot1<-interactions::interact_plot(familyTiesSocialContext_duration, pred="socialmedia.bp.z", modx="familyTiesNumeric.mean")
plot1<-plot1+theme_apa()+xlab("Social Media Use Duration (BP)")+ylab("Feelings of Being Accepted")+ggtitle("Family Ties (BP)")
ggsave("Interact: Family (BP) x Duration (BP).pdf")
plot2<-interactions::johnson_neyman(familyTiesSocialContext_duration, pred="socialmedia.bp.z", modx="familyTiesNumeric.mean")
plot2<-plot2$plot+theme_apa()+xlab("Family Ties (BP)") +ylab("Slope of Social Media Use Duration and Accepted")
plot2
ggsave("JN: Family (BP) x Duration (BP).pdf")
```

```{r, sig-results-9, echo=FALSE}
summary(natureContext_duration) ## Significant
plot1<-interactions::interact_plot(natureContext_duration, pred="socialmedia.cz", modx="home_natureNumeric.mean")
plot1<-plot1+theme_apa()+xlab("Social Media Use Duration (WP)")+ylab("Feelings of Being Accepted")+ggtitle("Nature Locations (BP)")
plot1
ggsave("Interact: Nature (BP) x Duration (WP).pdf")
plot2<-interactions::johnson_neyman(natureContext_duration, pred="socialmedia.cz", modx="home_natureNumeric.mean")
plot2<-plot2$plot+theme_apa()+xlab("Nature Locations (BP)") +ylab("Slope of Social Media Use Duration and Accepted")
plot2
ggsave("JN: Nature (BP) x Duration (WP).pdf")
```


```{r, sig-results-10, echo=FALSE}
summary(transitContext_duration) ## Trending
plot1<-interactions::interact_plot(transitContext_duration, pred="socialmedia.bp.z", modx="home_transitNumeric.scaled")
plot1<-plot1+theme_apa()+xlab("Transit Locations (WP)")+ylab("Feelings of Being Accepted")+ggtitle("Social Media Use Duration (BP)")
plot1
ggsave("Interact: Transit (WP) x Duration (BP).pdf")
plot2<-interactions::johnson_neyman(transitContext_duration, pred="socialmedia.bp.z", modx="home_transitNumeric.scaled")
plot2<-plot2$plot+theme_apa()+xlab("Social Media Use Duration (BP)") +ylab("Slope of Transit Locations and Accepted")
plot2
ggsave("JN: Transit (WP) x Duration (BP).pdf")
```

```{r, sig-results-11, echo=FALSE}
summary(transitContext_duration) ## Trending
plot1<-interactions::interact_plot(transitContext_duration, pred="socialmedia.bp.z", modx="home_transitNumeric.mean")
plot1<-plot1+theme_apa()+xlab("Social Media Use Duration (BP)")+ylab("Feelings of Being Accepted")+ggtitle("Transit Locations (BP)")
plot1
ggsave("Interact: Transit (BP) x Duration (BP).pdf")
plot2<-interactions::johnson_neyman(transitContext_duration, pred="socialmedia.bp.z", modx="home_transitNumeric.mean")
plot2<-plot2$plot+theme_apa()+xlab("Transit Locations (BP)") +ylab("Slope of Social Media Use Duration and Accepted")
ggsave("JN: Transit (BP) x Duration (BP).pdf")
```

```{r, sig-results-12, echo=FALSE}
summary(workContext_duration) ## Trending
plot1<-interactions::interact_plot(workContext_duration, pred="socialmedia.cz", modx="home_workNumeric.scaled")
plot1<-plot1+theme_apa()+xlab("Social Media Use Duration (WP)")+ylab("Feelings of Being Accepted")+ggtitle("Work Locations (WP)")
plot1
ggsave("Interact: Work (WP) x Duration (WP).pdf")
plot2<-interactions::johnson_neyman(workContext_duration, pred="socialmedia.cz", modx="home_workNumeric.scaled")
plot2<-plot2$plot+theme_apa()+xlab("Work Locations (WP)") +ylab("Slope of Social Media Use Duration and Accepted")
plot2
ggsave("JN: Work (WP) x Duration (WP).pdf")
```

```{r, save, echo=FALSE}
save.image(file = "accepted_exploratory.RData")
```
